//! Access policy of the device object: the pump is not open to every process.
//!
//! The whole IOCTL surface is `FILE_ANY_ACCESS` (see [`crate::ioctl`]), and most
//! of it is not diagnostics: `SET_MODE`, `SET_CHARGE` and `SET_LIMITS` change
//! what the pump does to the battery, and `WRITE_REG` writes a chip register
//! directly. There is no requestor check anywhere in the driver - no
//! `RequestorMode`, no privilege test - so the security descriptor on the device
//! object is the only gate there is. Without one, the object carries the WDF
//! default for its device type, and any process on the tablet, including a
//! sandboxed application, can open the device and drive the pump.
//!
//! The descriptor below is applied by the framework every time the device is
//! created, which is why it lives in code rather than only in the INF: the
//! hardware key that holds the INF's `Security` value is rewritten when the
//! driver is reinstalled, while this call runs on every start.
//!
//! `D:P(A;;GA;;;SY)(A;;GA;;;BA)` is a protected DACL (no inherited entries)
//! granting `GENERIC_ALL` to `LocalSystem` and to the built-in Administrators
//! group, and nothing to anyone else. It is the same string as the WDK constant
//! `SDDL_DEVOBJ_SYS_ALL_ADM_ALL`.
//!
//! # The device must be named first
//!
//! A security descriptor cannot be attached to an unnamed device object, and the
//! documentation of `WdfDeviceInitAssignSDDLString` states the precondition
//! plainly: the driver must call `WdfDeviceInitAssignName`, or it must call
//! `WdfDeviceInitSetCharacteristics` with `FILE_AUTOGENERATED_DEVICE_NAME`.
//! A PnP device must not name its own object - the PnP manager owns that - so
//! the second form is the one to use, and [`allow_security_descriptor`] does it.
//!
//! Skipping that step is not a visible error at the point of the mistake. The
//! assignment itself returns `STATUS_SUCCESS`; the rejected descriptor is
//! discovered later, inside `WdfDeviceCreate`, as
//! `STATUS_INVALID_SECURITY_DESCR` (`0xC0000079`), and the device then fails to
//! start with `CM_PROB_FAILED_ADD` (31). Measured on the tablet with driver
//! 20.47.10.664: the `SddlSt` mark read `0` while the driver stopped at stage
//! `STAGE_DEVICE`. Two earlier hypotheses - a missing NUL terminator and a
//! `const` array whose temporary does not outlive the call - were both wrong;
//! the terminator and the `static` below are kept because they match the
//! canonical `DECLARE_CONST_UNICODE_STRING` form, not because either was the fix.
//!
//! Two things this deliberately does not do. It does not tighten the control
//! codes themselves: they stay access-agnostic because the user-mode tool opens
//! the device once and issues both read and write codes through that one handle,
//! and because the access field is part of the code value, which the deployed
//! tooling has baked in. The DACL is the boundary; the access field is not.
//!
//! It also does not cover the device node. The PDO is created by the ACPI bus
//! driver before this driver sees the device, and the device interface resolves
//! to that PDO, so the interface carries the bus driver's descriptor rather than
//! this one. The INF sets the same policy on the node (an INF `Security` value
//! under the hardware key); the two together cover both open paths, the symbolic
//! link `\\.\nabu_ln8000` through this descriptor and the device interface
//! through the INF's.
//!
//! A consequence to know before using the tooling in `deploy/`: a process that is
//! not elevated does not match `(A;;GA;;;BA)` even when its user is an
//! administrator, because a filtered token carries the group for deny-only. The
//! tools that open the device therefore have to run elevated. Reading the
//! telemetry marks does not: those are registry values.

use wdk_sys::{
    call_unsafe_wdf_function_binding, FILE_AUTOGENERATED_DEVICE_NAME, NTSTATUS, PWDFDEVICE_INIT,
    UNICODE_STRING,
};

/// Access policy: `LocalSystem` and Administrators, nothing else.
const SDDL_TEXT: &str = "D:P(A;;GA;;;SY)(A;;GA;;;BA)";

/// The text as UTF-16 **plus a terminating zero**.
///
/// `WdfDeviceInitAssignSDDLString` hands the buffer to the SDDL parser, which
/// reads a null-terminated string. `DECLARE_CONST_UNICODE_STRING` in C counts the
/// terminator in `MaximumLength` for the same reason. Without it the parser walks
/// past the end of the array.
const SDDL_CHARS: usize = SDDL_TEXT.len() + 1;

/// The descriptor in UTF-16, zero-terminated. Only used to check and to initialise
/// [`SDDL`]; the pointer that goes to WDF must be the static's.
const SDDL_INIT: [u16; SDDL_CHARS] = ascii_utf16(SDDL_TEXT);

/// The descriptor handed to WDF. **A `static`, not a `const`.**
///
/// The framework is not documented to copy the string, and a `const` array is
/// materialised as a temporary at each point of use, so a `const` here would
/// leave WDF holding a pointer to storage that may already be gone by the time it
/// parses the string. A `static` has one address for the life of the driver.
static SDDL: [u16; SDDL_CHARS] = SDDL_INIT;

/// Length in bytes, the way `UNICODE_STRING` counts: without the terminating zero.
const SDDL_BYTES: u16 = (SDDL_TEXT.len() as u16) * 2;

/// Buffer size in bytes, the way `UNICODE_STRING` counts it: with the zero.
const SDDL_MAX_BYTES: u16 = (SDDL_CHARS as u16) * 2;

// Checked at compile time, because the failure mode is invisible until the driver
// runs: a missing terminator costs the whole device, and the crate's tests cannot
// run on the host (`no_std` and the test harness conflict), so a `#[test]` here
// would never execute.
const _: () = assert!(SDDL_INIT[SDDL_CHARS - 1] == 0);
const _: () = assert!(SDDL_MAX_BYTES == SDDL_BYTES + 2);

/// ASCII to UTF-16 at compile time, leaving the last element as the zero terminator.
const fn ascii_utf16(text: &str) -> [u16; SDDL_CHARS] {
    let bytes = text.as_bytes();
    let mut out = [0_u16; SDDL_CHARS];
    let mut index = 0;
    while index < bytes.len() {
        out[index] = bytes[index] as u16;
        index += 1;
    }
    out
}

/// Asks WDF for an autogenerated name for the device object.
///
/// This is the documented precondition of
/// [`WdfDeviceInitAssignSDDLString`](assign): a descriptor is only legal on a
/// named object. It has to happen before the descriptor is assigned, and it
/// returns nothing, so a mistake here is not reported by this call - it surfaces
/// as a `WdfDeviceCreate` failure with `STATUS_INVALID_SECURITY_DESCR`. See the
/// module documentation.
///
/// # Safety
///
/// `device_init` must be the structure WDF passed to `EvtDriverDeviceAdd` and
/// must still be owned by the driver, that is, the device must not have been
/// created from it yet.
unsafe fn allow_security_descriptor(device_init: PWDFDEVICE_INIT) {
    // SAFETY: `device_init` is valid until the device is created.
    unsafe {
        call_unsafe_wdf_function_binding!(
            WdfDeviceInitSetCharacteristics,
            device_init,
            FILE_AUTOGENERATED_DEVICE_NAME,
            // `OrInValues`: keep whatever the PnP manager has already set.
            1_u8,
        )
    };
}

/// Applies the access policy to the device that is being created.
///
/// Must be called before `WdfDeviceCreate`: the descriptor is stored in the
/// initialisation structure and consumed when the device object is built.
///
/// A failure is returned to the caller so that it is visible, but it is **not**
/// recoverable: the initialisation structure keeps the rejected descriptor, and
/// the subsequent `WdfDeviceCreate` fails with the same status. The caller
/// therefore proceeds and records the code as the `SddlSt` mark - a device that
/// reports its problem from a mark is easier to diagnose than one that refuses to
/// start, and there is no way to un-assign the string from here.
///
/// # Safety
///
/// `device_init` must be the structure WDF passed to `EvtDriverDeviceAdd` and
/// must still be owned by the driver, that is, the device must not have been
/// created from it yet.
pub unsafe fn assign(device_init: PWDFDEVICE_INIT) -> NTSTATUS {
    // SAFETY: the caller guarantees `device_init` is still owned by the driver.
    unsafe { allow_security_descriptor(device_init) };
    let mut sddl = UNICODE_STRING {
        Length: SDDL_BYTES,
        MaximumLength: SDDL_MAX_BYTES,
        Buffer: SDDL.as_ptr().cast_mut(),
    };
    // SAFETY: `device_init` is valid until the device is created, and `sddl`
    // points at a static buffer that outlives the call.
    unsafe {
        call_unsafe_wdf_function_binding!(
            WdfDeviceInitAssignSDDLString,
            device_init,
            &raw mut sddl,
        )
    }
}
